import { Poppins, Roboto } from "next/font/google";
import "./globals.css?ver=2";


const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
})

export const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],

})
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={` h-full antialiased`}
      data-theme="light"
    >
      <body className={`${poppins.className} min-h-full flex flex-col`}>
        <div className="conainer mx-auto max-w-6xl px-5">

          {children}
        </div>
      </body>
    </html>
  );
}
